services:
  - type: web
    name: n8n
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: DB_TYPE
        value: postgresdb
      - key: DB_POSTGRESDB_HOST
        value: <your-postgres-host>
      - key: DB_POSTGRESDB_PORT
        value: "5432"
      - key: DB_POSTGRESDB_DATABASE
        value: <your-db-name>
      - key: DB_POSTGRESDB_USER
        value: <your-db-user>
      - key: DB_POSTGRESDB_PASSWORD
        value: <your-db-password>
      - key: N8N_BASIC_AUTH_USER
        value: admin
      - key: N8N_BASIC_AUTH_PASSWORD
        value: supersecurepassword
      - key: WEBHOOK_URL
        value: https://<render-subdomain>.onrender.com/
      - key: N8N_ENCRYPTION_KEY
        generateValue: true
